### ISSUE TITLE
Add local path for the lottie json

### ISSUE THREAD

**Issue by Muhammad-Ashik** [arthurdenner/remotion-lottie-test#4]
Hey there! This repo was suggested by Remotion Creator. Currently we get the json from url but I want to add local json to the path. Could you please help me on it?

**Comment by arthurdenner** [comment]
Hi @Muhammad-Ashik! 👋🏽 

`lottie-web` supports a parameter called `animationData` when loading the animation ([docs](http://airbnb.io/lottie/#/web?id=usage)).
In the case of a local file, that's what we should use instead of the `path` parameter.

I'll have a look at adding an example for this as well.

**Comment by arthurdenner** [comment]
I've added an example in https://github.com/arthurdenner/remotion-lottie-test/pull/5.
Please note the workaround to call `continueRender` manually since Lottie doesn't fire the same event when loading through a file.
I'll investigate this a bit more and open an issue on their repo if needed.
I hope the example allows you to move forward for now. 🙌🏽

**Comment by arthurdenner** [comment]
Exploring a bit more, I decided to rely on the `DOMLoaded` event (https://github.com/arthurdenner/remotion-lottie-test/pull/6).
It fires for both `animationData` and `path` so it's better than a workaround.

**Comment by Muhammad-Ashik** [comment]
@arthurdenner Hey thank you buddy. I am now using your latest changes. But having another issue. I am modifying the JSON programmatically. Whenever I send updated JSON to RemotionLottie component the animation immediately hide. If I click on play or seek the player slider the animation shows immediately with the updated change. So I think it is not re rendering. I tried to modify your code but I'm not getting success. Could you please help me on that?
